### ISSUE TITLE
Docs: Add documentation on webhooks

### ISSUE THREAD

**Issue by samtstern** [GoogleCloudPlatform/repository-gardener#47]
I'd like to be able to tell DPEBot to merge when green, but I am not sure how to set up the webhooks.

**Comment by jonparrott** [comment]
Just create an issue, assign it to dpebot, and title it "Add webhook".

**Comment by samtstern** [comment]
@jonparrott but what do all the webhooks do? Is there a way to select some and not others?  For example I want the merging webhook but I don't want dpebot doing any issue management.

**Comment by jonparrott** [comment]
dpebot doesn't do any issue management yet (just automerge). If we add more bells and whistles I'll also create a nice control panel for it.

**Comment by samtstern** [comment]
Oh ok I thought I read something about it auto-assigning itself to all issues.
