### ISSUE TITLE
DPEBot is not auto-accepting invites

### ISSUE THREAD

**Issue by samtstern** [GoogleCloudPlatform/repository-gardener#49]
![tfrwibojs7z](https://user-images.githubusercontent.com/8466666/36165361-2aa099ac-10a4-11e8-8181-4f3401defa22.png)

This is on firebase/friendlyeats-android, I invited DPEBot yesterday.  This is causing builds on that repo to fail.

**Comment by jonparrott** [comment]
I forgot to deploy cron.yaml. Should be all fixed now.
